### ISSUE TITLE
kipavois-0.1.2  All request thrown an error

### ISSUE THREAD

**Issue by mojira98** [cogniteev/kipavois#2]
Hello,

When testing kipavois on elasticsearch v 2.1 with kibana 4,
i've the same error with multiple configuration :

nginx -> kipavois -> kibana -> elastic
nginx -> kibana -> kipavois -> elastic ...

Thanks!

```
proxy listen 9200

info: GET /


/usr/lib/node_modules/kipavois/node_modules/http-proxy/lib/http-proxy/index.js:119
    throw err;
          ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
```

**Comment by tristan0x** [comment]
Hey @mojira98 ,
according to your pull request #3, I guess you figured what went wrong. If so, do you confirm this issue can be closed ?

**Comment by mojira98** [comment]
Yes ! it's solved  :-)
